### ISSUE TITLE
Feature Request: add support for handling `zg`/`zug`

### ISSUE THREAD

**Issue by kevin61416** [neoclide/coc-typos#3]
**coc-typos** does not update  anything when using `zg` to add a good word in 'spellfile'.

My current workaround is:
1. manually run `:CocCommand typos.reloadSpellfile` command
2. run `e` command to re-edit and refresh coc-typos in the current file 

Expected Solution:
Provide a function or plugin-mapping to **incrementally** add/del good word in coc-typos and the 'spellfile' , rather than reloading **entire** 'spellfile'.

**Comment by chemzqm** [comment]
Spell files are already watched https://github.com/neoclide/coc-typos/blob/f305c8bcd8545cb57a3b06c2eaff2822cc3757ba/src/ignored.ts#L35

don't know why it not works for you.

**Comment by kevin61416** [comment]
Sorry for late reply, I missed the notification.

You are right, spell files has been updated; it's actual another issue:
I add a **wrong** good word.

For example, coc-typos found a typo: `mak` in a word “project_mak” (it suggests fixing to **make**).
Then, I try to add `mak` as a good word by `zg`; however, Vim adds “project_mak” as good word rather than `mak`, therefore, coc-typos still suggests me to fix `mak`.

Would you provide a way to let `zg` adds the right good word without manually select the misjudge part by user?

**Comment by chemzqm** [comment]
It's vim's behavior, you can use visual mode or `:CocCommand typos.addToSpellfile` which added on 0.2.0.
