### ISSUE TITLE
Bug? Black highlight with black text color

### ISSUE THREAD

**Issue by mentos1386** [neoclide/coc-typos#4]
Hi. I'm having an issue with `coc-typos-fix`. It results in black highlighted with black text color:

![image](https://user-images.githubusercontent.com/1910649/185350929-789d436e-9bed-4c18-906b-821159d8b434.png)

I'm using [onhalflight](https://github.com/sonph/onehalf/blob/master/vim/colors/onehalflight.vim) theme.

**Comment by chemzqm** [comment]
`:h CocMenuSel`

**Comment by mentos1386** [comment]
Thanks. I switched to https://github.com/sainnhe/edge if anyone else wants similar looking light theme with better support for coc.

**Comment by chemzqm** [comment]
You only need add a line like
```
hi link CocMenuSel YourGroup
```
to your vimrc.
